### ISSUE TITLE
lang .txt

### ISSUE THREAD

**Issue by Berbestean** [danielvoicu136/gameplay_cstrike_war3re#2]
[AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\war3FT.txt

**Comment by danielvoicu136** [comment]
hello , lang file is now included

**Comment by Berbestean** [comment]
frate tu ai severul pe daeva?

**Comment by danielvoicu136** [comment]
da eu sunt unul dintre oamenii care au daeva

**Comment by Berbestean** [comment]
Pai ce ai tu pe sv e si aici?

**Comment by danielvoicu136** [comment]
da , exact
