### ISSUE TITLE
.INC

### ISSUE THREAD

**Issue by Berbestean** [danielvoicu136/gameplay_cstrike_war3re#3]
Biblioteci la el nu are in compilator da multe erori

**Comment by danielvoicu136** [comment]
ce erori primesti in consola ? ( sa stiu ce librari sa pun , nu foloseste custom nimic )

**Comment by Berbestean** [comment]
Pai ceva de la libraria hud si inca 38 nu mai stiu exact iti trimit dupa sevici SS

**Comment by danielvoicu136** [comment]
incearca sa folosesti libraria standard de dhud 

https://forums.alliedmods.net/showthread.php?t=149210
